# Exercise 1
$\frac{1}{e^{z_{t}} K_{t}^{\alpha}-K_{t+1}}=\beta E_{t}\left\{\frac{\alpha e^{z_{t+1}} K_{t+1}^{\alpha-1}}{e^{z_{t+1}} K_{t+1}^{\alpha}-K_{t+2}}\right\}$

$K_{t+1}=A e^{z_{t}} K_{t}^{\alpha}$

$\frac{1}{e^{z_{t}} K_{t}^{\alpha}-K_{t+1}}=\beta E_{t}\left\{\frac{\alpha e^{z_{t+1}} K_{t+1}^{\alpha-1}}{e^{z_{t+1}} K_{t+1}^{\alpha}-A e^{z_{t+1}} K_{t+1}^{\alpha}}\right\}$

$\frac{1}{e^{z_{t}} K_{t}^{\alpha}-K_{t+1}}=\beta E_{t}\left\{\frac{\alpha  K_{t+1}^{\alpha-1}}{ K_{t+1}^{\alpha}-A  K_{t+1}^{\alpha}}\right\}$

Do more substitutions and arrive at: 
$K_{t+1}=\frac{\beta \alpha}{1-A+\beta \alpha}e^{z_t}K_t^\alpha$

$A=\frac{\beta \alpha}{1-A+\beta \alpha}$

and so 

$A=\beta \alpha$


# Exercise 2
Characteristic equations: 

### Intertemporal Euler equation: 
$u_{c}\left(c_{t}, \ell_{t}\right)=\beta E_{t}\left\{u_{c}\left(c_{t+1}, \ell_{t+1}\right)\left[\left(r_{t+1}-\delta\right)(1-\tau)+1\right]\right\}$

### Consumption leisure Euler:
    
$-u_{\ell}\left(c_{t}, \ell_{t}\right)=u_{c}\left(c_{t}, \ell_{t}\right) w_{t}(1-\tau)$

### Firm: 

$R_{t}=f_{K}\left(K_{t}, L_{t}, z_{t}\right)$

$W_{t}=f_{L}\left(K_{t}, L_{t}, z_{t}\right)$

where 

$u_c(c_t, l_t)=\frac{1}{c_t}$

$u_l(c_t, l_t)=\frac{-a}{1-l_t}$

and 

$F_k (K_{t}, L_{t}, z_{t}) =\alpha K_{t}^{\alpha-1}e^{z_{t}} L_{t}^{1-\alpha}$

$F_L (K_{t}, L_{t}, z_{t}) =(1-\alpha) K_{t}^{\alpha}e^{z_{t}} L_{t}^{-\alpha}$

I think we can as we have a Cobb Douglas plus log utility. My guess would be: 

$K_{t+1}=Ae^{z_t}K_t^\alpha L_t^{1-\alpha}$

where A are depends on $\alpha$ and $\beta$

# Exercise 3: 
As above, where: 


$u_c(c_t, l_t)=c_t^{-\gamma}$

$u_l(c_t, l_t)=\frac{-a}{1-l_t}$

and 

$F_k (K_{t}, L_{t}, z_{t}) =\alpha K_{t}^{\alpha-1}e^{z_{t}} L_{t}^{1-\alpha}$

$F_L (K_{t}, L_{t}, z_{t}) =(1-\alpha) K_{t}^{\alpha}e^{z_{t}} L_{t}^{-\alpha}$


# Exercise 4: 
As above, where: 


$u_c(c_t, l_t)=c_t^{-\gamma}$

$u_l(c_t, l_t)=a(1-\ell_t)^{-\xi}$

and 


$F\left(K_{t}, L_{t}, z_{t}\right)=e^{z_{t}}\left[\alpha K_{t}^{\eta}+(1-\alpha) L_{t}^{\eta}\right]^{\frac{1}{\eta}}$

$F_K\left(K_{t}, L_{t}, z_{t}\right)=e^{z_{t}}\left[\alpha K_{t}^{\eta}+(1-\alpha) L_{t}^{\eta}\right]^{\frac{1-\eta}{\eta}}\eta K_t^{\eta-1}\alpha$

$F_L\left(K_{t}, L_{t}, z_{t}\right)=e^{z_{t}}\left[\alpha K_{t}^{\eta}+(1-\alpha) L_{t}^{\eta}\right]^{\frac{1-\eta}{\eta}}\eta L_t^{\eta-1}(1-\alpha)$

# Exercise 5: 

$V\left(k_{t} ; \theta_{t}\right)=\max _{\ell_{t}, k_{t+1}} u\left(c_{t}, \ell_{t}\right)+\beta E_{t}\left\{V\left(k_{t+1}, \theta_{t+1}\right)\right\}$


s.t. $(1-\tau)\left[w_{t} \ell_{t}+\left(r_{t}-\delta\right) k_{t}\right]+k_{t}+T_{t}=c_{t}+k_{t+1}$

### Intertemporal Euler equation: 
$u_{c}\left(c_{t}, \ell_{t}\right)=\beta E_{t}\left\{u_{c}\left(c_{t+1}, \ell_{t+1}\right)\left[\left(r_{t+1}-\delta\right)(1-\tau)+1\right]\right\}$

### Consumption leisure Euler:
    
$-u_{\ell}\left(c_{t}, \ell_{t}\right)=u_{c}\left(c_{t}, \ell_{t}\right) w_{t}(1-\tau)$

### Firm: 

$R_{t}=f_{K}\left(K_{t}, L_{t}, z_{t}\right)$
$W_{t}=f_{L}\left(K_{t}, L_{t}, z_{t}\right)$

# Exercise 5: 

$\begin{aligned} u\left(c_{t}\right) &=\frac{c_{t}^{1-\gamma}-1}{1-\gamma} \\ F\left(K_{t}, L_{t}, z_{t}\right) &=K_{t}^{\alpha}\left(L_{t} e^{z_{t}}\right)^{1-\alpha} \end{aligned}$

## MUC: 

$ u_c\left(c_{t}\right) =c_{t}^{-\gamma}$


FOCs FIRM: 

$F_k (K_{t}, L_{t}, z_{t}) =\alpha K_{t}^{\alpha-1}e^{z_{t}(1-\alpha)} L_{t}^{1-\alpha}$

$F_L (K_{t}, L_{t}, z_{t}) =(1-\alpha) K_{t}^{\alpha}e^{z_{t}(1-\alpha)} L_{t}^{-\alpha}$

## Steady State
$c=(1-\tau)[w+(r-\delta) k]+T$


$c^{-\gamma}=\beta \left\{c^{-\gamma}[(r-\delta)(1-\tau)+1]\right\}$


$r=\alpha k^{\alpha-1}e^{z(1-\alpha)}$


$w=(1-\alpha) k^{\alpha}e^{z(1-\alpha)} $


$\tau[w+(r-\delta) k]=T$

## Rewrite: 


$\frac{\frac{1}{\beta }-1}{(1-\tau)}+\delta=(\alpha k^{\alpha-1}e^{z(1-\alpha)})$


$\{ \frac{1}{\alpha}\frac{1-\beta}{\beta}\frac{1}{1-\tau}e^{-z(\alpha-1)} \}^{\frac{1}{\alpha-1}}=k$

## Now put stuff in solver

In [28]:
import scipy as scipy
import sympy as sy
from scipy import stats
from scipy.stats import norm
import numpy as np
from matplotlib import pyplot as plt
from scipy.optimize import root
import scipy.optimize as opt
from scipy.integrate import quad
from matplotlib import pyplot as plt
from scipy.interpolate import CubicSpline

In [29]:
def fun(x):
    tau=.05
    z=0
    delta=.1
    alpha=.4
    beta=.98
    gamma=2.5
    #x=[x1h1, x2h1,x1h2, x2h2,p1,p2]
    c=x[0]
    k=x[1]
    r=x[2]
    w=x[3]
    T=x[4]    
    return \
    [c-(1-tau)*(w+(r-delta)*k)+T,
    c**(-gamma)-beta*c**(-gamma)*((r-delta)*(1-tau)+1),
    r-alpha*k**(alpha-1)*np.exp(z*(1-alpha)),
    w-(1-alpha)*k**alpha*np.exp(z*(1-alpha)),
    tau*(w+(r-delta)*k)-T]

In [30]:
sol=scipy.optimize.root(fun, [0.5,0.5,0.5, 0.5,0.5])
print(sol.x)

[1.33605434 7.28749795 0.12148228 1.32795277 0.07422524]


# Exercise 6

$\begin{aligned} u\left(c_{t}, \ell_{t}\right) &=\frac{c_{t}^{1-\gamma}-1}{1-\gamma}+a \frac{\left(1-\ell_{t}\right)^{1-\xi}-1}{1-\xi}  \\  F\left(K_{t}, L_{t}, z_{t}\right) &=K_{t}^{\alpha}\left(L_{t} e^{z t}\right)^{1-\alpha} \end{aligned}$

$ u_c(c_{t}, \ell_{t}) =c_{t}^{-\gamma}$

$ u_\ell(c_{t}, \ell_{t}) =-a (1-\ell_{t})^{-\xi}$



### Steady State

$\overline{c}=(1-\tau)[\overline{w} \overline{\ell}+(\overline{r}-\delta) \overline{k}]+\overline{T}$

$c^{-\gamma}=\beta c^{-\gamma}[(\overline{r}-\delta)(1-\tau)+1]$

$a (1-\ell)^{-\xi}=c^{-\gamma} \overline{w}(1-\tau)$


$r=\alpha k^{\alpha-1}e^{z(1-\alpha)}$


$w=(1-\alpha) k^{\alpha}e^{z(1-\alpha)} $


$\tau[\overline{w} \overline{\ell}+(\overline{r}-\delta) \overline{k}]=\overline{T}$

In [43]:
def fun5(x):
    tau=.05
    z=0
    delta=.1
    alpha=.4
    beta=.98
    gamma=2.5
    xi=1.5
    a=.5
    #x=[x1h1, x2h1,x1h2, x2h2,p1,p2]
    c=x[0]
    k=x[1]
    r=x[2]
    w=x[3]
    T=x[4] 
    l=x[5]
    return \
    [c-(1-tau)*(w*l+(r-delta)*k)+T,
    c**(-gamma)-beta*c**(-gamma)*((r-delta)*(1-tau)+1),
    a*(1-l)**(-xi)-c**(-gamma)*w*(1-tau),
    r-alpha*k**(alpha-1)*np.exp(z*(1-alpha)),
    w-(1-alpha)*k**alpha*np.exp(z*(1-alpha)),
    tau*(w*l+(r-delta)*k)-T]

In [44]:
sol=scipy.optimize.root(fun5, [0.5,0.5,0.5, 0.5,0.5, 0.5])
print(sol.x)

[0.84704808 7.28749795 0.12148228 1.32795277 0.04705823 0.59084366]


# Q7 

In [52]:
tau=.05
z_bar=0
delta=.1
alpha=.4
beta=.98
gamma=2.5
xi=1.5
a=.5
    
def getA(z_bar, alpha):
    A = np.exp(z_bar*(1-alpha))
    return A

def getC(tau, w, r, delta, k, T, l):
    c = (1-tau)*(w*l + (r-delta)*k) + T
    return c

def getR(alpha, z_bar, k, l):
    A = getA(z_bar, alpha)
    r=alpha*k**(alpha-1)*A
    return r

def getW(alpha, z_bar, k, l):
    A = getA(z_bar, alpha)
    w=(1-alpha)*k**alpha*A
    return w

def getT(tau, w, r, delta, k, l):
    T = tau*(w*l + (r-delta)*k)
    return T

def getY(alpha, z_bar, k,l):
    A = getA(z_bar,alpha)
    Y = A*(k**alpha)*l**(1-alpha)
    return Y

def euler(klvec, *args):
    (alpha, z_bar, tau, delta, gamma, beta, a, zeta) = args
    k = klvec[0]
    l = klvec[1]
    r = getR(alpha, z_bar, k,l)
    w = getW(alpha, z_bar, k,l)
    T = getT(tau, w, r, delta, k,l)
    c = getC(tau, w, r, delta, k, T,l)
    error1 = c**(-gamma)-beta*c**(-gamma)*((r-delta)*(1-tau)+1)
    error2 = a*(1-l)**(-xi)-c**(-gamma)*w*(1-tau)
    errors = np.array([error1, error2])
    return errors

def ss_func(alpha, z_bar, tau, delta, gamma, beta, a, xi):
    klvec_init = np.array([0.5,0.5]) #initialize search
    EEargs = (alpha, z_bar, tau, delta, gamma, beta, a, xi)
    results = opt.root(euler, klvec_init, args= (EEargs), tol = 1e-14)
    klvec_ss = results.x
    errors = results.fun
    k_ss = klvec_ss[0]
    l_ss = klvec_ss[1]
    Y = getY(alpha, z_bar, k_ss, l_ss)
    r = getR(alpha, z_bar, k_ss, l_ss)
    w = getW(alpha, z_bar, k_ss, l_ss)
    T = getT(tau, w, r, delta, k_ss, l_ss)
    C = getC(tau, w, r, delta, k_ss, T, l_ss)
    I = delta*k_ss
    return k_ss, C, r, w, l_ss, T, Y, I
ssvalues=ss_func(alpha, z_bar, tau, delta, gamma, beta, a, xi)
print(ssvalues)

(7.287497950692989, 0.8921243068256077, 0.12148227712137488, 1.3279527683513057, 0.553914471853246, 0.04460621534128039, 1.5527337947723057, 0.7287497950692989)


In [53]:
derivative = np.empty((8, 8))
epsilon = 1e-4

#Add epsilon
gamma_p  = gamma+epsilon
zeta_p = zeta + epsilon
beta_p = beta + epsilon
alpha_p = alpha + epsilon
delta_p = delta + epsilon
z_bar_p = z_bar + epsilon
tau_p = tau + epsilon
a_p = a + epsilon

# Matrix with perturbed parameters
derivative[0,:] = ss_func(alpha, z_bar, tau, delta_p, gamma, beta, a, zeta)
derivative[1,:] = ss_func(alpha, z_bar, tau_p, delta, gamma, beta, a, zeta)
derivative[2,:] = ss_func(alpha, z_bar_p, tau, delta, gamma, beta, a, zeta)
derivative[3,:] = ss_func(alpha_p, z_bar, tau, delta, gamma, beta, a, zeta)
derivative[4,:] = ss_func(alpha, z_bar, tau, delta, gamma_p, beta, a, zeta)
derivative[5,:] = ss_func(alpha, z_bar, tau, delta, gamma, beta, a, zeta_p)
derivative[6,:] = ss_func(alpha, z_bar, tau, delta, gamma, beta_p, a, zeta)
derivative[7,:] = ss_func(alpha, z_bar, tau, delta, gamma, beta, a_p, zeta)

#matrix with original parameters
matrix = np.empty((8,8))
for i in range(8):
    matrix[i,:] = ss_func(alpha, z_bar, tau, delta, gamma, beta, a, zeta)

#derivative: (difference in perturbed steady state and original values)/epsilon 
derivative = (derivative - matrix)/epsilon
derivative

array([[-9.98706388e+01, -3.96183090e+00,  1.00000000e+00,
        -7.28250259e+00,  1.67078093e+00, -1.98091545e-01,
        -5.70679263e+00, -2.70955299e+00],
       [-2.26102789e+00, -2.08761830e-01,  2.26153038e-02,
        -1.64806424e-01, -1.75991129e-01,  8.81665339e-01,
        -4.88704365e-01, -2.26102789e-01],
       [ 7.28786234e+00,  6.10949160e-01,  6.93889390e-13,
         1.32801917e+00, -2.11748219e-01,  3.05474580e-02,
         1.19662936e+00,  7.28786234e-01],
       [ 5.45138062e+01,  2.33281712e+00, -3.19189120e-12,
         4.39780036e+00, -9.59256239e-01,  1.16640856e-01,
         7.03506409e+00,  5.45138062e+00],
       [ 1.77635684e-10,  2.13981272e-02, -1.80411242e-12,
         1.33226763e-11,  1.61136207e-02,  1.06990636e-03,
         2.71018182e-02,  1.77635684e-11],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.09702581e+02,  5.517189