# Problem 1

In [11]:
import numpy as np

In [8]:
def myfun(A, B):
    C=np.array(A)
    D=np.array(B)
    E=np.dot(C,D)
    return E


In [9]:
A=[[3,-1,4],[1,5,-9]]
B=[[2, 6, -5, 3],[5, -8, 9, 7],[9, -3, -2, -3]]

In [10]:
myfun(A,B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

# Problem 2

In [12]:
A=[[3,1,4],[1,5,9],[-5,3,1]]

In [24]:
def myfun2(A):
    B=np.array(A)
    C=np.dot(A,A)
    D=np.dot(C,A)
    E=-D+9*C-15*B
    return E

In [25]:
myfun2(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Problem 3

In [57]:
def myfun3():
    A=np.ones((7,7), dtype=np.int)   
    mat1=np.triu(A)
    a=np.triu(np.full((7,7),5),k=1)
    b=np.tril(np.full((7,7),-1))
    mat2=a+b
    res1=np.dot(mat1,mat2)
    res2=np.int64(np.dot(res1,mat1))
    return res2

In [58]:
myfun3()

array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]], dtype=int64)

# Problem 4


In [93]:
def myfun4(x):
    x1=np.array(x)
    x2=x1
    mask=x1<0
    x2[mask]=0
    return x2

In [96]:
x=[-2, 34,-5,234,-49, -237482]

In [97]:
myfun4(x)

array([  0,  34,   0, 234,   0,   0])

# Problem 5

In [140]:
def myfun5():
    A=np.array([[0,2,4],[1,3,5]])
    B=np.array([[3,0,0],[3,3,0],[3,3,3]])
    C=-2*np.eye(3)
    I=np.eye(3)
    row1=np.hstack((np.zeros((3,4)),np.transpose(A), I))
    row2=np.hstack((A,np.zeros((2,3)),np.zeros((2,3))))
    row3=np.hstack((B,np.zeros((3,3)),C))
    results=np.vstack((row1, row2, row3))
    return results

In [141]:
myfun5()

array([[ 0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.,  0., -2., -0., -0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -0., -2., -0.],
       [ 3.,  3.,  3.,  0.,  0.,  0., -0., -0., -2.]])

# Problem 6

In [172]:
def myfun6(A):
    x=np.array(A)
    div=np.sum(x,1).reshape(2,1)
    res=A/div
    return res

In [175]:
A=[[2,3,4],[4,5,6]]
myfun6(A)

array([[0.22222222, 0.33333333, 0.44444444],
       [0.26666667, 0.33333333, 0.4       ]])

# Problem 7

In [259]:
grid = np.load("grid.npy")

In [267]:
horiz=np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])

In [268]:
vert=np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])

In [269]:
diag1=np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])

In [270]:
diag2=np.max(grid[:-3,3:] * grid[1:-2,1:-2]* grid[2:-1,2:-1] * grid[3:,:-3])

In [271]:
totalmax=np.max(np.array([horiz,vert,diag1,diag2]))

In [272]:
print(totalmax)

51267216
